### ISSUE TITLE
Error while make install : recipe for target 'local' failed

### ISSUE THREAD

**Issue by C0deDaedalus** [varlesh/VLC-Breeze#1]
I cloned your repository and inside that issued this command

` $ sudo make install`

and got the following errors.

**find Breeze{,-Fixed-Size}.vlt -type f -exec install -Dm644 '{}' "/usr/share/vlc/skins2/{}" \;
find: ‘Breeze{,-Fixed-Size}.vlt’: No such file or directory 
Makefile:11: recipe for target 'local' failed 
make: *** [local] Error 1** 

Please look into it and solve it.

**Comment by varlesh** [comment]
fixed
