### ISSUE TITLE
VLC 3.x Support

### ISSUE THREAD

**Issue by saeidscorp** [varlesh/VLC-Breeze#3]
VLC 3 no longer accepts these themes. It would be nice to have it in VLC 3!

**Comment by varlesh** [comment]
Why not?
worked:
![image](https://user-images.githubusercontent.com/8083855/51548920-bacba200-1e82-11e9-8eab-164697f178d3.png)

**Comment by saeidscorp** [comment]
It fails with this error:
![failure](https://user-images.githubusercontent.com/3063549/51550462-a044f900-1e81-11e9-8c6b-336ea3222812.png)
I don't know what I've done wrong :(

**Comment by varlesh** [comment]
@saeidscorp Why your skin have another name? Maybe you use not my skin. Try install from Git.
My LOG:
```
alex@pc:~$ vlc
VLC media player 3.0.4 Vetinari (revision 3.0.4-0-gf615db6332)
Icon theme "gnome" not found.
[000055ccbe7b1010] skins2 interface: skin: Breeze  author: varlesh
[000055ccbe7b1010] skins2 interface error: pls, check resize policy for id: fs_playpause
[000055ccbe6ce4e0] main playlist: playlist is empty
```
Skin have error with resize policy, but runing and worked

**Comment by varlesh** [comment]
Error `pls, check resize policy for id: fs_playpause` fixed:
![image](https://user-images.githubusercontent.com/8083855/51582121-1e39ec00-1ee4-11e9-9654-81fa7afc0ac7.png)

**Comment by saeidscorp** [comment]
No, I downloaded it from KDE Look. After seeing this error, I thought it might have something to do with the zip structure of the `vlt` file. So I moved the contents up one directory and zipped it again to test it (and renamed the downloaded file to `Breeze-orig.vlt`).

I even tried the git repo (before and now, after your latest commit) to no avail:

![git](https://user-images.githubusercontent.com/3063549/51605459-5e20c380-1f24-11e9-9859-685c730400f9.png)

I'm on Gentoo, compiled VLC with these USE flags:

```
[I] media-video/vlc
     Installed versions:  3.0.4(0/5-9)(20:54:15 01/20/19)
     (X a52 alsa bidi bluray chromecast dbus dts dvbpsi dvd encode ffmpeg flac fontconfig gcrypt
      gstreamer jack jpeg libass libcaca libnotify libsamplerate live lua matroska mp3 mpeg mtp
      musepack ncurses ogg opus png postproc pulseaudio qt5 samba skins speex ssl svg theora
      truetype udev upnp v4l vaapi vnc vorbis x264 x265 xml zeroconf
      -altivec -aom -archive -aribsub 
      -cddb -chromaprint -dc1394 -debug -directx -faad -fdk -fluidsynth -gme -gnome-keyring -ieee1394 
      -kate -libav -libtar -libtiger -linsys -lirc -macosx-notifications -macosx-qtkit -modplug -neon -nfs
      -omxil -opencv -optimisememory -projectm -rdp -run-as-root -sdl-image -sftp -shout -sid -soxr -srt
      -taglib -test -tremor -twolame -vdpau -vpx -wayland -wma-fixed -zvbi
      CPU_FLAGS_X86="mmx sse")
```

**Comment by varlesh** [comment]
@saeidscorp I can't help you. I think it's compiling flags issue... 
You seen my screens - it's worked fine with Kde Neon (Ubuntu 18.04) and VLC 3.0.4
VLT - it's renamed zip-archive, you can unpack and check all files, if needed

**Comment by saeidscorp** [comment]
OK thanks for your time :)
